#Setting the logging levels for the service
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jiker.authentication.dao.domain
logging:
  level:
    com.jiker.oauth.dao : debug
