server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jiker.info.dao.domain
logging:
  level:
    com.jiker.oauth.dao : debug
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8081/user
